#!/usr/bin/env bash
# lint-skills.sh — invariants the sprint skills must hold. Prose is the product; lint it.
set -uo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
ORCH="$HERE/../sprint-orchestrator/SKILL.md"
ORCH_REF="$HERE/../sprint-orchestrator/REFERENCE.md"
ORCH_YAML="$HERE/../sprint-orchestrator/agents/openai.yaml"
ORCH_README="$HERE/../sprint-orchestrator/README.md"
PASS=0; FAIL=0
ok() { PASS=$((PASS+1)); printf 'ok   - %s\n' "$1"; }
no() { FAIL=$((FAIL+1)); printf 'FAIL - %s\n' "$1"; }
has()   { grep -qF -- "$2" "$3" && ok "$1" || no "$1 (missing: $2)"; }
hasnt() { grep -qF -- "$2" "$3" && no "$1 (found: $2)" || ok "$1"; }

# --- sprint-orchestrator ---
hasnt "orchestrator: no CLAIMED state"      ".CLAIMED.md"        "$ORCH"
hasnt "orchestrator: no done/ archive"      "done/"              "$ORCH"
hasnt "orchestrator: no unconditional 'do not merge'" "do not merge" "$ORCH"
hasnt "orchestrator: no checkout of trunk"  "git checkout main"  "$ORCH"
hasnt "orchestrator: no HANDOFF.md"         "HANDOFF.md"         "$ORCH"
hasnt "orchestrator: no dead mode field"    "mode: shaped"       "$ORCH"
hasnt "orchestrator: no narrow story glob"  "[0-9][0-9]-*.md"    "$ORCH"
has   "orchestrator: names sprint-status"   "sprint-status.sh"   "$ORCH"
has   "reference: conversation field"       "conversation:"      "$ORCH_REF"
has   "reference: execution field"          "execution:"         "$ORCH_REF"
has   "reference: frontend field"           "frontend:"          "$ORCH_REF"
has   "reference: surfaces field"           "surfaces:"          "$ORCH_REF"
has   "reference: browser verification"     "## Browser Verification" "$ORCH_REF"
has   "reference: owns_hunk promoted"       "owns_hunk:"         "$ORCH_REF"
has   "reference: wave promoted"            "wave:"              "$ORCH_REF"
has   "orchestrator: loop field"            "loop:"              "$ORCH"
has   "orchestrator: driver_hint field"     "driver_hint:"       "$ORCH"
has   "reference: driver_why field"         "driver_why:"        "$ORCH_REF"
has   "orchestrator: tier field"            "tier:"              "$ORCH"
has   "reference: tier_why field"           "tier_why:"          "$ORCH_REF"
has   "reference: effort_why field"         "effort_why:"        "$ORCH_REF"
has   "reference: orchestrate field"        "orchestrate:"       "$ORCH_REF"
has   "reference: orchestrate implies xhigh" "implies xhigh"     "$ORCH_REF"
has   "reference: effort only on deviation" "only when the story deviates" "$ORCH_REF"
has   "orchestrator: tier from nature only" "tier:\` derives from the work's nature" "$ORCH"
orch_rows="$(grep -E '^\| [SABC] \|' "$ORCH_REF")"
[ "$(printf '%s\n' "$orch_rows" | grep -c .)" = 4 ] \
  && ok "orchestrator: ladder has exactly 4 tier rows" \
  || no "orchestrator: ladder has exactly 4 tier rows (got: $(printf '%s\n' "$orch_rows" | grep -c .))"
has   "orchestrator: capability outranks affinity" "Capability outranks affinity" "$ORCH"
# The running agent must never reason about its own model. Launch advice is README-only:
# frontmatter description is harness-visible and could re-trigger self-disqualification.
hasnt "orchestrator: no self-model gate"        "Strongest Model"    "$ORCH"
hasnt "orchestrator: no self-identification"    "name the model you are running as" "$ORCH"
hasnt "orchestrator: no relaunch offer"         "so the user can relaunch" "$ORCH"
hasnt "orchestrator: no strongest-model remnant" "strongest-model"   "$ORCH"
hasnt "orchestrator: no launch advice in frontmatter" "Best run on"  "$ORCH"
has   "orchestrator readme: where-to-run advice" "## Where to run it" "$ORCH_README"
has   "orchestrator readme: fable preferred"     "Fable"             "$ORCH_README"
has   "orchestrator: incremental waves"     "wave boundary"      "$ORCH"
has   "orchestrator: deferred stories are stubs" "stub"          "$ORCH"
hasnt "orchestrator: no filesystem ledger claim" "filesystem remains the ledger" "$ORCH"
hasnt "orchestrator: no filesystem-backed desc" "filesystem-backed" "$ORCH"
has   "reference: kickoff line addresses planner, not executor" "executor does not run this" "$ORCH_REF"
# The two agents guard implicit invocation with different keys. Both must be set, or the skill
# silently becomes model-invocable on one side. Claude: SKILL.md. Codex: agents/openai.yaml.
has   "orchestrator: claude blocks implicit invocation" "disable-model-invocation: true" "$ORCH"
has   "orchestrator: codex blocks implicit invocation"  "allow_implicit_invocation: false" "$ORCH_YAML"
# DONE needs BOTH trailers. Story numbers restart each sprint, so `Story: NN` alone collides.
done_row=$(grep -F '| `DONE` |' "$ORCH")
case "$done_row" in
  *Sprint*) ok "orchestrator: DONE row requires the Sprint trailer too" ;;
  *) no "orchestrator: DONE row requires the Sprint trailer too (found: $done_row)" ;;
esac
has   "orchestrator: loop is a judgment call"   "judgment call, not a tier rule" "$ORCH"
has   "orchestrator: brainstorm cue"            "design space is open"     "$ORCH"
has   "orchestrator: direct cue"                "well-trodden in-repo pattern" "$ORCH"
has   "reference: REPLAN event heading"     "## REPLAN — rp-"     "$ORCH_REF"
has   "reference: DIRECTION event heading"  "## DIRECTION — dr-"  "$ORCH_REF"
has   "reference: RESOLUTION event heading" "## RESOLUTION —"     "$ORCH_REF"
has   "reference: pre-dispatch REVIEW event" "## REVIEW — rv-"    "$ORCH_REF"
has   "reference: wave RETRO event"         "## RETRO — rt-"      "$ORCH_REF"
has   "reference: wave-scoped event ids"    "rv-YYYYMMDD-w"       "$ORCH_REF"
has   "orchestrator: reviews see full sprint"   "full sprint as context"   "$ORCH"
has   "orchestrator: review is judgment not gate" "is your judgment"       "$ORCH"
has   "orchestrator: cross-family review"       "cross-family"             "$ORCH"
has   "reference: handoff names the retro"  "Wave retro:"              "$ORCH_REF"
has   "reference: recap template names the critic" "Critic: <rv-id | none" "$ORCH_REF"
has   "reference: skipped read never silent" "never as silence"        "$ORCH_REF"
has   "reference: events are immutable"     "Never edit an existing event" "$ORCH_REF"
has   "reference: direction flow value"     "# mechanical | design-heavy | direction" "$ORCH_REF"
has   "reference: dossier naming"           "dossier-NN.md"            "$ORCH_REF"
has   "orchestrator: subagents gated on recap"  "user approves the recap"  "$ORCH"
has   "reference: publish before firing"    "Publish before firing"    "$ORCH_REF"
has   "orchestrator: one planner per sprint dir" "One planner per sprint dir" "$ORCH"
has   "reference: sweep checks unmerged sprint-docs" "sprint-docs/" "$ORCH_REF"
has   "orchestrator: brief gate section"        "## The Sprint Brief" "$ORCH"
has   "orchestrator: brief lands in overview"   "## Sprint brief"     "$ORCH"
has   "orchestrator: brief legacy case"         "do not force a backfill" "$ORCH"
has   "orchestrator: brief partial case"        "Never run first-run creation" "$ORCH"
has   "orchestrator: point of contact"          "## Point of Contact" "$ORCH"
has   "orchestrator: supervising section"       "## Supervising the Wave" "$ORCH"
has   "orchestrator: merge-order dispatch constraint" "merge-order-independent" "$ORCH"
has   "orchestrator: trailer-preserving merge"  "must preserve trailers" "$ORCH"
has   "orchestrator: post-merge DONE check"     "after the merge" "$ORCH"
has   "orchestrator: mailbox never state"       "The mailbox is never state" "$ORCH"
has   "orchestrator: reactive mailbox watch"    "watch the mailbox reactively" "$ORCH"
has   "reference: supervisor arm globs"       "'*-question.md *-concluded.md'" "$ORCH_REF"
has   "reference: codex re-arm carries --harness"  "arm --harness codex <sprint-dir> '*-question.md *-concluded.md' 1800" "$ORCH_REF"
has   "reference: claude re-arm at idle budget"    "arm --harness claude <sprint-dir> '*-question.md *-concluded.md' 10800" "$ORCH_REF"
has   "reference: supervisor parks via supervise" "sprint-mail.sh supervise --harness" "$ORCH_REF"
has   "reference: kimi park has goal-less fallback" "ending the turn is the park" "$ORCH_REF"
has   "reference: kimi sweep creates only if absent" "CronList first" "$ORCH_REF"
has   "orchestrator: kimi invocation spelling"        "/skill:sprint-orchestrator" "$ORCH"
grep -q '^description: "' "$ORCH" && ok "orchestrator: description is a quoted scalar" || no "orchestrator: description is a quoted scalar"
has   "reference: kimi supervisor sweep is a recurring cron" "recurring cron" "$ORCH_REF"
has   "reference: kimi skills-dir status path"     "~/.agents/skills/sprint-orchestrator/sprint-status.sh" "$ORCH_REF"
has   "orchestrator: kimi death clause"               "never be resumed" "$ORCH"
hasnt "orchestrator: no kimi hook installer"          "install-kimi-hook" "$ORCH"
hasnt "reference: no kimi hook installer"             "install-kimi-hook" "$ORCH_REF"
has   "reference: supervisor is a main session"   "the supervisor is always a main session" "$ORCH_REF"
has   "reference: subagent kickoffs render subagent topology" "--topology subagent" "$ORCH_REF"
hasnt "orchestrator: no background-task wait"         "as a background task" "$ORCH"
has   "reference: sweep unread first"           "sprint-mail.sh unread" "$ORCH_REF"
hasnt "orchestrator: no epoch dance"            "re-arm with the epoch of that sweep" "$ORCH"
has   "orchestrator: read-cursor never state"   "nor the read-cursor" "$ORCH"
has   "orchestrator: rescue bound by contract"  "following EXECUTION.md like any executor" "$ORCH"
has   "orchestrator: planner owns loop call"    "the planner owns it" "$ORCH"
has   "orchestrator: ownership transfer section" "## Ownership Transfer" "$ORCH"
has   "orchestrator: never take over live"       "Never take over a live executor" "$ORCH"
has   "orchestrator: grant grammar"              "resume designated branch" "$ORCH"
has   "reference: DISPOSED heading"           "## DISPOSED — dp-"  "$ORCH_REF"
has   "orchestrator: disposed is wave accounting" "wave accounting, never DONE" "$ORCH"
has   "reference: story-scoped event ids"     "rp-YYYYMMDD-NN-"    "$ORCH_REF"
has   "orchestrator: planner handoff section"   "## The Planner Handoff" "$ORCH"
has   "reference: handoff goal spans the wave" "and the next planner handoff rendered" "$ORCH_REF"
has   "reference: sprint-terminal variant"    "### Sprint-terminal variant" "$ORCH_REF"
has   "reference: terminal handoff keeps the skill call" "Sprint complete:" "$ORCH_REF"
has   "reference: scope leads are pointers"   "to verify, not decisions" "$ORCH_REF"
has   "orchestrator: terminal handoff carries the call" "the handoff still carries the skill call" "$ORCH"
has   "orchestrator: scope stays with the brief gate" "never authored scope" "$ORCH"
has   "orchestrator: demotion cutover"          "solely as the leftover's executor" "$ORCH"
hasnt "orchestrator: handoff never asks identity" "identify its model" "$ORCH"

# --- constitution pins (the restructured SKILL.md's load-bearing prose) ---
has   "constitution: mandate section"         "## The Mandate"     "$ORCH"
has   "constitution: executive owns the sprint" "this seat is executive" "$ORCH"
has   "constitution: operator bears the risk" "bears the risk"     "$ORCH"
has   "constitution: vital signs section"     "## Vital Signs"     "$ORCH"
has   "constitution: facts of reality"        "Facts of reality"   "$ORCH"
has   "constitution: things to do"            "Things to do"       "$ORCH"
has   "constitution: decision rights section" "## Decision Rights" "$ORCH"
has   "constitution: critic section"          "## The Critic"      "$ORCH"
has   "constitution: critic before recap"     "before the recap"   "$ORCH"
has   "constitution: critic advisory"         "never enforced"     "$ORCH"
has   "constitution: recap plan is the read plan" "the plan the Critic must have read" "$ORCH"
has   "constitution: replan closed by rebuttal" "a rebuttal round on the same" "$ORCH"
has   "constitution: stage is a vital sign"  "project stage"           "$ORCH"
has   "constitution: no per-stage table"     "per-stage table:"        "$ORCH"
has   "constitution: stage weighs exposure"  "fact of reality about exposure" "$ORCH"
has   "constitution: stage transition is operator's" "a stage transition —" "$ORCH"
has   "constitution: points at reference"     "REFERENCE.md"       "$ORCH"
has   "reference: constitution wins on disagreement" "the constitution wins and this file is stale" "$ORCH_REF"

# --- agent-handoff (SKILL.md) ---
AH="$HERE/../agent-handoff/SKILL.md"
# Frontmatter sanity without a YAML parser: name matches the directory, and the description is a
# quoted scalar — the retired codex-execution-handoff description was unquoted, contained
# "Triggers:", and silently failed YAML parsing. Grep can prevent that class.
grep -q '^name: agent-handoff$' "$AH" 2>/dev/null && ok "handoff: name matches directory" || no "handoff: name matches directory"
grep -q '^description: "' "$AH" 2>/dev/null && ok "handoff: description is a quoted scalar" || no "handoff: description is a quoted scalar"
hasnt "handoff: model-invocable (no manual-only guard)" "disable-model-invocation" "$AH"
has   "handoff: /goal ends every prompt"     "/goal"              "$AH"
has   "handoff: names Codex.app"             "Codex.app"          "$AH"
has   "handoff: report-only default"         "Report-only by default" "$AH"
has   "handoff: mutation grant"              "mutation grant"     "$AH"
has   "handoff: workspace identity (SHA)"    "HEAD SHA"           "$AH"
has   "handoff: task files in ~/.handoffs"   "~/.handoffs"        "$AH"
has   "handoff: EXECUTION MODE inline"       "EXECUTION MODE"     "$AH"
has   "handoff: stop-at-pr rendered loud"    "STOP AT PR — DO NOT MERGE OR DEPLOY" "$AH"
has   "handoff: codex contract path"         "~/.codex/skills/agent-handoff/EXECUTION.md" "$AH"
has   "handoff: claude contract path"        "~/.claude/skills/agent-handoff/EXECUTION.md" "$AH"
has   "handoff: kimi target"                 "| \`kimi\`" "$AH"
has   "handoff: kimi contract path"          "~/.agents/skills/agent-handoff/EXECUTION.md" "$AH"
has   "handoff: kimi wait form"              "Kimi has no Stop-hook wait" "$AH"
hasnt "handoff: no kimi hook installer"      "install-kimi-hook" "$AH"
has   "handoff: task mode excludes sprint stories" "numbered sprint story" "$AH"
has   "handoff: capability outranks affinity" "Capability outranks affinity" "$AH"
has   "handoff: hard rules name the story trailer"  "Story: {NN}"   "$AH"
has   "handoff: hard rules name the sprint trailer" "Sprint: {SPRINT}" "$AH"
bad=$(grep -nF 'git checkout main' "$AH" 2>/dev/null | grep -viE 'never|do not|don.t|instead of' || true)
[ -z "$bad" ] && ok "handoff: git checkout main only ever negated" || no "handoff: git checkout main appears as an instruction ($bad)"
has   "handoff: Launch line rendered"        "Launch:"            "$AH"
has   "handoff: Launch line outside the fence" "outside the fenced prompt block" "$AH"
has   "handoff: luna orchestration bump"     "bumps to Terra"     "$AH"
has   "handoff: recommended base invocation" "recommended base invocation" "$AH"
grep -qE 'gpt-5\.6-luna.*`high`' "$AH" \
  && ok "handoff: visual-validation defaults luna+high on one line" \
  || no "handoff: visual-validation defaults luna+high on one line"
ah_rows="$(grep -E '^\| [SABC] \|' "$AH")"
[ "$(printf '%s\n' "$ah_rows" | grep -c .)" = 4 ] \
  && ok "handoff: ladder has exactly 4 tier rows" \
  || no "handoff: ladder has exactly 4 tier rows (got: $(printf '%s\n' "$ah_rows" | grep -c .))"
[ -n "$orch_rows" ] && [ "$orch_rows" = "$ah_rows" ] \
  && ok "ladder: orchestrator and handoff tables in sync" \
  || no "ladder: orchestrator and handoff tables diverge"
# kimi-k3 sits between fable and sol: the S row's Kimi cell, fable's capacity substitute.
printf '%s\n' "$orch_rows" | grep -qF '| S | `fable` | — | `kimi-k3` |' \
  && ok "ladder: S row carries the kimi-k3 cell" || no "ladder: S row carries the kimi-k3 cell"
hasnt "orchestrator: no stale no-Kimi-cell wording" "the ladder has no Kimi cell" "$ORCH"
hasnt "handoff: no stale no-Kimi-cell wording"     "the ladder has no Kimi cell" "$AH"
has   "handoff: codex cli-vs-app question"       "does this need a browser, or a human in the loop" "$AH"
has   "handoff: codex-cli base invocation bypasses" "--dangerously-bypass-approvals-and-sandbox" "$AH"
has   "handoff: interactive depth line"      "investigation + interactive brainstorm phase with the operator first" "$AH"
hasnt "handoff: no self-directed wording"    "self-directed brainstorm" "$AH"
has   "handoff: settled by default"          "settled by default" "$AH"
hasnt "handoff: no hard SETTLED wording"     "are SETTLED"        "$AH"
has   "handoff: handback hard rule"          "publish the REPLAN event" "$AH"
has   "handoff: direction renders no skills" "\`flow: direction\` → none" "$AH"
has   "handoff: never renders brainstorming skill" "Never render superpowers:brainstorming" "$AH"
has   "handoff: mailbox line in template"    "Mailbox: {MAILBOX}" "$AH"
has   "handoff: mailbox wait line in template" "Mailbox wait: {" "$AH"
has   "handoff: reviews route to orchestrator" "the sprint orchestrator is your only counterparty" "$AH"
has   "handoff: codex wait form is arm-and-end-turn" "arm --harness codex {SPRINT_DIR} {NN}-{SSS}-reply.md 1800" "$AH"
has   "handoff: claude wait form is arm-and-end-turn" "arm --harness claude {SPRINT_DIR} {NN}-{SSS}-reply.md 1800" "$AH"
has   "handoff: subagent renders non-arming fallback" "Do not pretend to wait" "$AH"
has   "handoff: mis-scoped direct story note" "re-planned as a main-session story" "$AH"
hasnt "handoff: no background-task wait"     "as a background task" "$AH"
has   "handoff: takeover render rule"            "Resume grant:"      "$AH"
has   "handoff: ordinary kickoffs still refuse"  "Ordinary kickoffs never carry it" "$AH"
has   "handoff: hard rule carries grant carve-out" "unless this kickoff carries a resume grant" "$AH"

# --- agent-handoff (EXECUTION.md, the lifecycle contract) ---
AHEXEC="$HERE/../agent-handoff/EXECUTION.md"
has   "contract: story trailer"              "Story: {NN}"        "$AHEXEC"
has   "contract: sprint trailer"             "Sprint:"            "$AHEXEC"
has   "contract: worktree-safe branching"    "git switch -c"      "$AHEXEC"
has   "contract: refuses a taken story"      "already exists"     "$AHEXEC"
has   "contract: resume grant exception"         "resume grant"       "$AHEXEC"
has   "contract: approved drivers"           "approved driver"    "$AHEXEC"
has   "contract: bans DOM substitution"      "DOM"                "$AHEXEC"
has   "contract: evidence outside the repo"  ".sprint-evidence"   "$AHEXEC"
has   "contract: stop-at-pr collapse"        "do not merge, do not deploy" "$AHEXEC"
has   "contract: tracker done intent"        "card.done"          "$AHEXEC"
has   "contract: third interrupt condition"  "approved driver can drive" "$AHEXEC"
has   "contract: first interrupt condition"  "wrong premise"      "$AHEXEC"
has   "contract: second interrupt condition" "keep prod green"    "$AHEXEC"
has   "contract: orchestration never waives the contract" "never waives this contract" "$AHEXEC"
hasnt "contract: no per-sprint HANDOFF.md"   "HANDOFF.md"         "$AHEXEC"
hasnt "contract: no CLAIMED rename"          ".CLAIMED.md"        "$AHEXEC"
hasnt "contract: no strongest-model remnant"  "strongest-model"    "$AHEXEC"
bad=$(grep -nF 'git checkout main' "$AHEXEC" 2>/dev/null | grep -viE 'never|do not|don.t|instead of' || true)
[ -z "$bad" ] && ok "contract: git checkout main only ever negated" || no "contract: git checkout main appears as an instruction ($bad)"
has   "contract: brainstorm gate section"    "## 2. Brainstorm gate" "$AHEXEC"
has   "contract: settled by default"         "settled by default" "$AHEXEC"
hasnt "contract: no hard SETTLED wording"    "are SETTLED"        "$AHEXEC"
has   "contract: hand-back-or-continue question" "hand back to sprint-orchestrator now, or continue?" "$AHEXEC"
has   "contract: REPLAN event heading"       "## REPLAN — rp-"    "$AHEXEC"
has   "contract: DIRECTION event heading"    "## DIRECTION — dr-" "$AHEXEC"
has   "contract: events publish without trailers" 'NO `Story:`/`Sprint:` trailers' "$AHEXEC"
has   "contract: claim released on handback" "Release the claim"  "$AHEXEC"
has   "contract: direction stories section"  "## Direction stories" "$AHEXEC"
has   "contract: dossier naming"             "dossier-{NN}.md"    "$AHEXEC"
has   "contract: stop-at-pr event merges before replan" "must merge BEFORE that re-invocation" "$AHEXEC"
has   "contract: claim deletion only when pure"  "only if the branch is still a pure claim" "$AHEXEC"
has   "contract: mailbox section"            "## Mailbox"         "$AHEXEC"
has   "contract: mailbox never state"        "The mailbox is never state" "$AHEXEC"
has   "contract: outcome enum"               "outcome: <merged | pr-ready | handback | blocked | failed | dossier>" "$AHEXEC"
has   "contract: mailbox degrades"           "degrades to the handback protocol" "$AHEXEC"
has   "contract: one open question"          "One open question at a time" "$AHEXEC"
has   "contract: notes read before merge"    "notes before merge or PR" "$AHEXEC"
has   "contract: note sweep via unread"      "sprint-mail.sh unread <sprint-dir> '{NN}-*-note.md'" "$AHEXEC"
has   "contract: read-cursor never state"    "nor the read-cursor" "$AHEXEC"
has   "contract: codex arm wait"             "sprint-mail.sh arm --harness codex <sprint-dir> {NN}-{SSS}-reply.md 1800" "$AHEXEC"
has   "contract: claude main-session arm wait" "sprint-mail.sh arm --harness claude <sprint-dir> {NN}-{SSS}-reply.md 1800" "$AHEXEC"
has   "contract: kimi wait form"             "Kimi has no Stop-hook wait" "$AHEXEC"
has   "contract: kimi cron"                  "CronCreate" "$AHEXEC"
hasnt "contract: no kimi hook installer"     "install-kimi-hook" "$AHEXEC"
has   "contract: subagent never arms"        "the Stop hook never fires for a subagent" "$AHEXEC"
hasnt "contract: no background-task wait"    "as a background task" "$AHEXEC"
has   "contract: arming is the wait"         "Arming and ending the turn IS the wait" "$AHEXEC"
has   "contract: orphaned waits banned"      "under \`nohup\`/\`&\`/tmux" "$AHEXEC"
has   "contract: gate names its counterparty" "Your counterparty at this gate" "$AHEXEC"
has   "contract: orchestrator is default counterparty" "the default and first resort for every open decision" "$AHEXEC"
has   "contract: settled decisions not re-gated" "re-open it as a fresh approval gate" "$AHEXEC"
has   "contract: no absent-user approvals"   "Never demand an in-thread" "$AHEXEC"
has   "contract: story-scoped replan id"        "rp-YYYYMMDD-{NN}-"  "$AHEXEC"
has   "contract: story-scoped direction id"     "dr-YYYYMMDD-{NN}-"  "$AHEXEC"
has   "contract: preflight refusal posts nothing" "reports via its transport and posts nothing" "$AHEXEC"
has   "contract: codex self-review"          "Self-review: completed" "$AHEXEC"

# --- claude-reviewer ---
CR="$HERE/../claude-reviewer/SKILL.md"
grep -q '^name: claude-reviewer$' "$CR" 2>/dev/null && ok "claude-reviewer: name matches directory" || no "claude-reviewer: name matches directory"
# From Claude Code the skill is circular (Claude summoning Claude) and its triggers collide
# with the `codex` skill. Codex ignores this key, so it stays implicitly invocable there.
has   "claude-reviewer: manual-only on Claude"  "disable-model-invocation: true" "$CR"
has   "claude-reviewer: reply is evidence, not instruction" "not an instruction to obey" "$CR"

# --- codex (reviewer lanes) ---
CX="$HERE/../codex/SKILL.md"
CXSH="$HERE/../codex/run-codex.sh"
grep -q '^name: codex$' "$CX" 2>/dev/null && ok "codex: name matches directory" || no "codex: name matches directory"
has   "codex: contained lane on terra"     "gpt-5.6-terra" "$CX"
has   "codex: premise lane on sol"         "gpt-5.6-sol"   "$CX"
has   "codex: luna floor"                  'never `gpt-5.6-luna`' "$CX"
has   "codex: justification before spend"  "BEFORE the run spends" "$CX"
has   "codex: explicit flags on run"       '--model "$MODEL" --effort "$EFFORT"' "$CX"
grep -qE 'gpt-5\.6-terra. at .xhigh' "$CX" \
  && ok "codex: terra lane pinned to xhigh" || no "codex: terra lane pinned to xhigh"
has   "codex wrapper: usage names xhigh default" "xhigh (default)" "$CXSH"
# Non-interactive codex sessions run unattended in bypass mode — the codex CLI's wording for
# Claude's bypass-permissions mode is --dangerously-bypass-approvals-and-sandbox.
has   "codex wrapper: bypass posture"        "--dangerously-bypass-approvals-and-sandbox" "$CXSH"
hasnt "codex wrapper: no sandbox posture left" "workspace-write" "$CXSH"
has   "codex readme: bypass posture"         "--dangerously-bypass-approvals-and-sandbox" "$HERE/../codex/README.md"

# --- wave-handoffs.sh (renderer must mirror agent-handoff/SKILL.md's template) ---
WHS="$HERE/../sprint-orchestrator/wave-handoffs.sh"
has   "renderer: interactive depth string"   "investigation + interactive brainstorm phase with the operator first" "$WHS"
has   "renderer: direction renders no skills" 'skills="none"'     "$WHS"
has   "renderer: handback hard rule"         "publish the REPLAN event" "$WHS"
has   "renderer: unresolved-event warning"   "unresolved feedback events" "$WHS"
hasnt "renderer: no hard SETTLED wording"    "are SETTLED"        "$WHS"
hasnt "renderer: no self-directed wording"   "self-directed brainstorm" "$WHS"
has   "renderer: mailbox line"               "sprint-mail"        "$WHS"
has   "renderer: mailbox wait line"          "Mailbox wait: "     "$WHS"
has   "renderer: reviews route to orchestrator" "the sprint orchestrator is your only counterparty" "$WHS"
has   "renderer: codex wait arms the hook"   "sprint-mail.sh arm" "$WHS"
has   "renderer: codex arm carries --harness"   "arm --harness codex" "$WHS"
has   "renderer: claude arm carries --harness"  "arm --harness claude" "$WHS"
has   "renderer: subagent fallback form"        "Do not pretend to wait" "$WHS"
has   "renderer: topology is a required input"  "--topology <main-session|subagent>" "$WHS"
has   "renderer: --target flag"                 "--target <codex|claude|kimi>" "$WHS"
has   "renderer: kimi-k3 is the S-tier Kimi cell" 'k_model="kimi-k3"' "$WHS"
has   "renderer: kimi wait form"                "Kimi has no Stop-hook wait" "$WHS"
hasnt "renderer: no kimi hook installer"        "install-kimi-hook" "$WHS"
hasnt "renderer: no background-task wait"       "as a background task" "$WHS"
hasnt "renderer: no unconditional parallel"  "These run in parallel" "$WHS"
hasnt "renderer: no brainstorming skill in kickoffs" 'skills="superpowers:brainstorming' "$WHS"

# --- codex-stop-wait.sh (the Codex Stop hook owning armed mailbox waits) ---
CSW="$HERE/../sprint-orchestrator/codex-stop-wait.sh"
SMAIL="$HERE/../sprint-orchestrator/sprint-mail.sh"
INSTALLER="$HERE/../sprint-orchestrator/install-codex-hook.sh"
[ -x "$CSW" ] && ok "stop-wait: hook exists and is executable" || no "stop-wait: hook exists and is executable"
has   "stop-wait: silent pass without a record" "exit 0" "$CSW"
has   "stop-wait: continuation via exit 2"      "exit 2" "$CSW"
has   "stop-wait: cursor reader"                "mode=cursor" "$CSW"
has   "stop-wait: legacy epoch reader"          "mode=epoch" "$CSW"
CLSW="$HERE/../sprint-orchestrator/claude-stop-wait.sh"
[ -x "$CLSW" ] && ok "claude-stop-wait: hook exists and is executable" || no "claude-stop-wait: hook exists and is executable"
has   "claude-stop-wait: Stop-only main sessions" "MAIN-session" "$CLSW"
has   "claude-stop-wait: silent pass without a record" "exit 0" "$CLSW"
has   "claude-stop-wait: continuation via exit 2"      "exit 2" "$CLSW"
# The two hook bodies (from `set -u` onward) must stay byte-identical: one source
# of truth for the wake logic. Only the leading harness header may differ.
if diff <(sed -n '/^set -u$/,$p' "$CSW") <(sed -n '/^set -u$/,$p' "$CLSW") >/dev/null 2>&1; then
  ok "claude-stop-wait: body in sync with codex-stop-wait"
else
  no "claude-stop-wait: body diverges from codex-stop-wait"
fi
has   "mail: arm usage line"                    "arm --harness <codex|claude> <sprint-dir> <name-or-glob(s)>" "$SMAIL"
has   "mail: disarm usage line"                 "disarm <sprint-dir>" "$SMAIL"
has   "mail: disarm --stale"                    "disarm <sprint-dir> [--stale]" "$SMAIL"
has   "mail: worktree-root cursor key"          "keyed by the worktree root" "$SMAIL"
has   "mail: arm refuses without wired hook"    "install-codex-hook.sh" "$SMAIL"
has   "mail: arm claude branch names installer" "install-claude-hook.sh" "$SMAIL"
has   "mail: arm requires --harness"            "arm requires --harness" "$SMAIL"
has   "mail: arm refuses kimi with redirect"    "Kimi has no Stop-hook wait" "$SMAIL"
hasnt "mail: no kimi hook installer"            "install-kimi-hook" "$SMAIL"
has   "mail: unread usage line"                 "unread <sprint-dir> <name-or-glob(s)>" "$SMAIL"
has   "mail: seen usage line"                   "seen <sprint-dir> <file>..." "$SMAIL"
has   "sprint-mail: usage names supervise"        "sprint-mail.sh supervise --harness <codex|claude|kimi> <sprint-dir>" "$SMAIL"
has   "sprint-mail: kimi payload goal-less park"  "ending the turn is the park" "$SMAIL"
[ -x "$INSTALLER" ] && ok "installer: exists and is executable" || no "installer: exists and is executable"
has   "installer: verifies trust, not just wiring" "reports '\$verify', not trusted" "$INSTALLER"
CLINSTALLER="$HERE/../sprint-orchestrator/install-claude-hook.sh"
[ -x "$CLINSTALLER" ] && ok "claude installer: exists and is executable" || no "claude installer: exists and is executable"
has   "claude installer: preserves co-installed hooks" "PRESERVING any co-installed" "$CLINSTALLER"
has   "claude installer: 10860 timeout"                '"timeout": 10860' "$CLINSTALLER"
has   "claude installer: no trust dance"               "No trust dance" "$CLINSTALLER"
has   "sprint readme: names the installer"      "install-codex-hook.sh" "$ORCH_README"
has   "sprint readme: names the claude installer" "install-claude-hook.sh" "$ORCH_README"
has   "sprint readme: kimi invocation spelling"   "/skill:sprint-orchestrator" "$ORCH_README"
has   "sprint readme: kimi waits need no install" "Reactive waits on Kimi" "$ORCH_README"
hasnt "sprint readme: no kimi hook installer"     "install-kimi-hook" "$ORCH_README"
has   "sprint readme: codex arm carries --harness" "arm --harness codex" "$ORCH_README"
has   "sprint readme: claude arm carries --harness" "arm --harness claude" "$ORCH_README"
has   "sprint readme: parallel-hook note"       "holds the Stop event's completion" "$ORCH_README"
has   "sprint readme: claude budget note"       "timeout: 10860" "$ORCH_README"
has   "sprint readme: topology flag documented" "--topology" "$ORCH_README"
has   "sprint readme: review moments"           "## RETRO — rt-" "$ORCH_README"
hasnt "sprint readme: no epoch mentions"        "epoch" "$ORCH_README"
has   "repo readme: names the hook setup"       "install-codex-hook.sh" "$HERE/../README.md"
has   "repo readme: names the claude hook setup" "install-claude-hook.sh" "$HERE/../README.md"

# --- INSTALL.md (the agent-facing setup guide the README points harnesses at) ---
INSTALL="$HERE/../INSTALL.md"
[ -f "$INSTALL" ] && ok "install guide: exists" || no "install guide: exists"
has   "install guide: links both harness dirs"  "CLAUDE_SKILLS_DIR=~/.codex/skills" "$INSTALL"
has   "install guide: kimi skills dir"          "CLAUDE_SKILLS_DIR=~/.agents/skills" "$INSTALL"
hasnt "install guide: no kimi hook installer"   "install-kimi-hook" "$INSTALL"
has   "install guide: wires the codex hook"     "install-codex-hook.sh" "$INSTALL"
has   "install guide: wires the claude hook"    "install-claude-hook.sh" "$INSTALL"
has   "install guide: runs the claude hook suite" "test-claude-stop-wait.sh" "$INSTALL"
has   "install guide: runs the claude installer suite" "test-install-claude-hook.sh" "$INSTALL"
has   "install guide: runs the lint"            "test/lint-skills.sh"   "$INSTALL"
has   "install guide: boundary rule"            "change nothing on this machine beyond what these steps name" "$INSTALL"
has   "repo readme: points agents at the guide" "Read ~/claude-skills/INSTALL.md and follow it" "$HERE/../README.md"

printf '\n%d passed, %d failed\n' "$PASS" "$FAIL"
[ "$FAIL" -eq 0 ]
